[build]
  command = "npm run generate"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  SECRETS_SCAN_OMIT_KEYS = "NUXT_PUBLIC_FIREBASE_API_KEY,NUXT_PUBLIC_FIREBASE_AUTH_DOMAIN,NUXT_PUBLIC_FIREBASE_PROJECT_ID,NUXT_PUBLIC_FIREBASE_STORAGE_BUCKET,NUXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,NUXT_PUBLIC_FIREBASE_APP_ID"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
